<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Test Results: All Tests</title>
<link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
</head>
<body onload="open('allclasses-frame.html','classListFrame')">
<h1>Test Results.</h1>
<h4>
<a href="file://localhost/Users/jdapper/Dev/Git/WebDriver/JunitTest/archive/" target="_blank">View Archive</a>
</h4>
<table width="100%">
<tr>
<td align="left"></td><td align="right">Salesforce WebDriver Framework 2014</td>
</tr>
</table>
<hr size="1">
<h2>All Tests</h2>
<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
<tr valign="top">
<th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th><th>Screenshots</th>
</tr>
<tr valign="top" class="Error">
<td><a href="com/salesforce/tests/suites/0_CategorySuite.html">CategorySuite</a></td><td><a name="testAddANewAccount_Sales"></a><a href="com/salesforce/tests/suites/0_CategorySuite.html#testAddANewAccount_Sales">testAddANewAccount_Sales</a></td><td>Error</td><td>Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'mreddy-ltr', ip: '10.106.62.169', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91' Driver info: driver.version: RemoteWebDriver<br>
<br>
<code>org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.<br>Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'<br>System info: host: 'mreddy-ltr', ip: '10.106.62.169', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'<br>Driver info: driver.version: RemoteWebDriver<br>	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)<br>	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)<br>	at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:131)<br>	at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:158)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.initDriver(Unknown Source)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.initializeClass(Unknown Source)<br>Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4001 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect<br>	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)<br>	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)<br>	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)<br>	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)<br>	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)<br>	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)<br>	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)<br>	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)<br>	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)<br>	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)<br>	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)<br>	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)<br>	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)<br>	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)<br>Caused by: java.net.ConnectException: Connection refused: connect<br>	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)<br>	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)<br>	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)<br>	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)<br>	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)<br>	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)<br>	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)<br>	at java.net.Socket.connect(Socket.java:589)<br>	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)<br>	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)<br>
</code>N/A<br>
<br>
<code>java.lang.ExceptionInInitializerError<br>	at com.salesforce.utils.datastore.FileIO.takeScreenShot(Unknown Source)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.tearDownTest(Unknown Source)<br>Caused by: java.lang.NullPointerException<br>	at com.salesforce.pages.PageBase.&lt;clinit&gt;(Unknown Source)<br>
</code></td><td>14.209</td><td><a href="../../images/testAddANewAccount_Sales">View</a></td>
</tr>
<tr valign="top" class="Error">
<td><a href="com/salesforce/tests/suites/0_CategorySuite.html">CategorySuite</a></td><td><a name="testAddANewContact_Sales"></a><a href="com/salesforce/tests/suites/0_CategorySuite.html#testAddANewContact_Sales">testAddANewContact_Sales</a></td><td>Error</td><td>Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'mreddy-ltr', ip: '10.106.62.169', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91' Driver info: driver.version: RemoteWebDriver<br>
<br>
<code>org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.<br>Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'<br>System info: host: 'mreddy-ltr', ip: '10.106.62.169', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'<br>Driver info: driver.version: RemoteWebDriver<br>	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)<br>	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)<br>	at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:131)<br>	at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:158)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.initDriver(Unknown Source)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.initializeClass(Unknown Source)<br>Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4001 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect<br>	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)<br>	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)<br>	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)<br>	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)<br>	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)<br>	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)<br>	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)<br>	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)<br>	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)<br>	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)<br>	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)<br>	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)<br>	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)<br>	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)<br>Caused by: java.net.ConnectException: Connection refused: connect<br>	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)<br>	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)<br>	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)<br>	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)<br>	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)<br>	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)<br>	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)<br>	at java.net.Socket.connect(Socket.java:589)<br>	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)<br>	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)<br>
</code>Could not initialize class com.salesforce.utils.driver.SalesforcePageExtensions<br>
<br>
<code>java.lang.NoClassDefFoundError: Could not initialize class com.salesforce.utils.driver.SalesforcePageExtensions<br>	at com.salesforce.utils.datastore.FileIO.takeScreenShot(Unknown Source)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.tearDownTest(Unknown Source)<br>
</code></td><td>13.284</td><td><a href="../../images/testAddANewContact_Sales">View</a></td>
</tr>
<tr valign="top" class="Error">
<td><a href="com/salesforce/tests/suites/0_CategorySuite.html">CategorySuite</a></td><td><a name="testAddANewOpportunity"></a><a href="com/salesforce/tests/suites/0_CategorySuite.html#testAddANewOpportunity">testAddANewOpportunity</a></td><td>Error</td><td>Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'mreddy-ltr', ip: '10.106.62.169', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91' Driver info: driver.version: RemoteWebDriver<br>
<br>
<code>org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.<br>Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'<br>System info: host: 'mreddy-ltr', ip: '10.106.62.169', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'<br>Driver info: driver.version: RemoteWebDriver<br>	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)<br>	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)<br>	at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:131)<br>	at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:158)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.initDriver(Unknown Source)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.initializeClass(Unknown Source)<br>Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4001 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect<br>	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)<br>	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)<br>	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)<br>	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)<br>	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)<br>	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)<br>	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)<br>	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)<br>	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)<br>	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)<br>	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)<br>	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)<br>	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)<br>	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)<br>Caused by: java.net.ConnectException: Connection refused: connect<br>	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)<br>	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)<br>	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)<br>	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)<br>	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)<br>	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)<br>	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)<br>	at java.net.Socket.connect(Socket.java:589)<br>	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)<br>	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)<br>
</code>Could not initialize class com.salesforce.utils.driver.SalesforcePageExtensions<br>
<br>
<code>java.lang.NoClassDefFoundError: Could not initialize class com.salesforce.utils.driver.SalesforcePageExtensions<br>	at com.salesforce.utils.datastore.FileIO.takeScreenShot(Unknown Source)<br>	at com.salesforce.tests.functionaltests.CloudBaseTest.tearDownTest(Unknown Source)<br>
</code></td><td>13.257</td><td><a href="../../images/testAddANewOpportunity">View</a></td>
</tr>
</table>
</body>
</html>
